name: hola mundo

on: 
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

jobs:
  hola:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      run: echo "Hello World"

    - name: Touch
      run: touch "hola.txt"

    - name: Text
      run: echo "Hola Mundo" >> hola.txt

    - name: Read
      run: cat hola.txt

  other:
    runs-on: ubuntu-latest
    needs: [hola]
    steps:
    - name: ls
      run: ls -al
